import numpy as np
import os
import random

def save_tsp_file(problem_name: str, 
                  coords: np.ndarray, 
                  data_dir: str = "data"):
    """
    Lưu một tập hợp tọa độ thành một file .tsp đơn giản.

    File này sẽ chứa siêu dữ liệu cơ bản và phần NODE_COORD_SECTION
    để tương thích với data_loader.py của chúng ta.

    Args:
        problem_name (str): Tên của vấn đề (ví dụ: 'test_10').
        coords (np.ndarray): Mảng (N, 2) của tọa độ [x, y].
        data_dir (str): Thư mục gốc chứa '/tsplib/'.
    """
    num_cities = coords.shape[0]
    
    # Đảm bảo thư mục /data/tsplib/ tồn tại
    tsp_dir = os.path.join(data_dir, "tsplib")
    if not os.path.exists(tsp_dir):
        os.makedirs(tsp_dir)
        
    file_path = os.path.join(tsp_dir, f"{problem_name}.tsp")
    
    try:
        with open(file_path, 'w') as f:
            f.write(f"NAME: {problem_name}\n")
            f.write(f"TYPE: TSP\n")
            f.write(f"COMMENT: Generated by TSP Project Generator\n")
            f.write(f"DIMENSION: {num_cities}\n")
            f.write(f"EDGE_WEIGHT_TYPE: EUC_2D\n")
            f.write(f"NODE_COORD_SECTION\n")
            
            # Ghi tọa độ (định dạng 1-indexed)
            for i in range(num_cities):
                # Định dạng: "ID X Y"
                f.write(f" {i+1} {coords[i, 0]:.4f} {coords[i, 1]:.4f}\n")
                
            f.write("EOF\n")
            
        print(f"Đã tạo file vấn đề thành công: {file_path}")
        
    except Exception as e:
        print(f"Lỗi khi lưu file {file_path}: {e}")

def generate_problem(problem_name: str, 
                     num_cities: int, 
                     max_coord: int = 1000, 
                     save_to_file: bool = True,
                     data_dir: str = "data") -> np.ndarray:
    """
    Tạo ra một vấn đề TSP mới với các tọa độ ngẫu nhiên.

    Args:
        problem_name (str): Tên để lưu file (ví dụ: 'test_10').
        num_cities (int): Số lượng thành phố (N).
        max_coord (int): Tọa độ tối đa (ví dụ: 1000 -> 0-999).
        save_to_file (bool): Nếu True, lưu file .tsp.
        data_dir (str): Thư mục data gốc.

    Returns:
        np.ndarray: Mảng (N, 2) của các tọa độ đã tạo.
    """
    # Tạo N cặp tọa độ (x, y) ngẫu nhiên, làm tròn thành số nguyên
    coords = np.random.randint(0, max_coord, size=(num_cities, 2))
    
    # Đảm bảo không có tọa độ trùng lặp (hiếm nhưng có thể xảy ra)
    unique_coords = np.unique(coords, axis=0)
    
    # Nếu có trùng lặp, tạo thêm cho đến khi đủ N
    while unique_coords.shape[0] < num_cities:
        needed = num_cities - unique_coords.shape[0]
        new_coords = np.random.randint(0, max_coord, size=(needed, 2))
        coords = np.vstack([unique_coords, new_coords])
        unique_coords = np.unique(coords, axis=0)
        
    coords = unique_coords
    
    if save_to_file:
        save_tsp_file(problem_name, coords, data_dir)
        
    return coords

# --- Ví dụ sử dụng (chỉ để kiểm tra nhanh) ---
if __name__ == "__main__":
    # File này phải nằm trong /utils/
    # Chúng ta muốn lưu vào /data/tsplib/
    
    # Giả định chạy từ thư mục gốc (hoặc 'data' nằm cùng cấp với 'utils')
    # Đường dẫn tương đối từ 'utils' lên thư mục gốc rồi xuống 'data'
    project_root_data_dir = os.path.join(os.path.dirname(__file__), '..', 'data')
    project_root_data_dir = os.path.normpath(project_root_data_dir)
    
    if not os.path.isdir(project_root_data_dir):
        print("Không tìm thấy thư mục 'data' ở cấp gốc. Thử ở thư mục hiện tại.")
        project_root_data_dir = "data" # Mặc định nếu chạy từ gốc
        
    print(f"Sử dụng thư mục data: {project_root_data_dir}")

    # --- Tạo file 'test_10.tsp' ---
    # File này rất quan trọng để chạy Brute Force
    print("\nĐang tạo 'test_10.tsp' (N=10)...")
    generate_problem(
        problem_name="test_10",
        num_cities=10,
        max_coord=100, # Giữ tọa độ nhỏ
        data_dir=project_root_data_dir
    )

    # --- Tạo file 'random_50.tsp' ---
    print("\nĐang tạo 'random_50.tsp' (N=50)...")
    generate_problem(
        problem_name="random_50",
        num_cities=50,
        max_coord=1000,
        data_dir=project_root_data_dir
    )
    
    print("\nKiểm tra Generator thành công!")