import numpy as np
import os
import random

def save_tsp_file(problem_name: str, 
                  coords: np.ndarray, 
                  data_dir: str = "data"):
    """
    Lưu một tập hợp tọa độ thành một file .tsp đơn giản.
    
    LƯU Ý: Lưu vào thư mục /data/generated/
    """
    num_cities = coords.shape[0]
    
    gen_dir = os.path.join(data_dir, "generated") 
    if not os.path.exists(gen_dir):
        os.makedirs(gen_dir)
        
    file_path = os.path.join(gen_dir, f"{problem_name}.tsp")
    
    try:
        with open(file_path, 'w') as f:
            f.write(f"NAME: {problem_name}\n")
            f.write(f"TYPE: TSP\n")
            f.write(f"COMMENT: Generated by TSP Project Generator\n")
            f.write(f"DIMENSION: {num_cities}\n")
            f.write(f"EDGE_WEIGHT_TYPE: EUC_2D\n")
            f.write(f"NODE_COORD_SECTION\n")
            
            for i in range(num_cities):
                f.write(f" {i+1} {coords[i, 0]:.4f} {coords[i, 1]:.4f}\n")
                
            f.write("EOF\n")
            
        print(f"Đã tạo file vấn đề thành công: {file_path}")
        
    except Exception as e:
        print(f"Lỗi khi lưu file {file_path}: {e}")

def generate_problem(problem_name: str, 
                     num_cities: int, 
                     max_coord: int = 1000, 
                     save_to_file: bool = True,
                     data_dir: str = "data") -> np.ndarray:
    """
    Tạo ra một vấn đề TSP mới với các tọa độ ngẫu nhiên.
    """
    coords = np.random.randint(0, max_coord, size=(num_cities, 2))
    unique_coords = np.unique(coords, axis=0)
    
    while unique_coords.shape[0] < num_cities:
        needed = num_cities - unique_coords.shape[0]
        new_coords = np.random.randint(0, max_coord, size=(needed, 2))
        coords = np.vstack([unique_coords, new_coords])
        unique_coords = np.unique(coords, axis=0)
        
    coords = unique_coords
    
    if save_to_file:
        save_tsp_file(problem_name, coords, data_dir)
        
    return coords